// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNvyblOXuzGxkP4MZts9BhznKaVEAf1c',
    appId: '1:204552340047:web:ee7fe8f0c24884e9d0203a',
    messagingSenderId: '204552340047',
    projectId: 'diploma-project-5a2f7',
    authDomain: 'diploma-project-5a2f7.firebaseapp.com',
    storageBucket: 'diploma-project-5a2f7.appspot.com',
    measurementId: 'G-EPQ737BGJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKzIJftyQVBtgQL9adh-bgcy2ttHugZms',
    appId: '1:204552340047:android:904518096070354fd0203a',
    messagingSenderId: '204552340047',
    projectId: 'diploma-project-5a2f7',
    storageBucket: 'diploma-project-5a2f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCUo2Q6_sLn8jy413BNeuRxz6eFZy3bVQ',
    appId: '1:204552340047:ios:c2b65abaf34527c1d0203a',
    messagingSenderId: '204552340047',
    projectId: 'diploma-project-5a2f7',
    storageBucket: 'diploma-project-5a2f7.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCUo2Q6_sLn8jy413BNeuRxz6eFZy3bVQ',
    appId: '1:204552340047:ios:5e1596a0a6eef932d0203a',
    messagingSenderId: '204552340047',
    projectId: 'diploma-project-5a2f7',
    storageBucket: 'diploma-project-5a2f7.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
